name: CI
on:
  pull_request:
    branches:
      - develop
      - master
      - release
      - main
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build
        run: mvn -B -ntp clean install
