name: CI
on:
  pull_request:
    branches:
      - develop
      - master
      - release
      - main
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando el codigo
        uses: actions/checkout@v5
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Compilar
        run: mvn -B -ntp clean install